// Generated by gencpp from file dynamo_planner/custom_states_msgs.msg
// DO NOT EDIT!


#ifndef DYNAMO_PLANNER_MESSAGE_CUSTOM_STATES_MSGS_H
#define DYNAMO_PLANNER_MESSAGE_CUSTOM_STATES_MSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamo_planner
{
template <class ContainerAllocator>
struct custom_states_msgs_
{
  typedef custom_states_msgs_<ContainerAllocator> Type;

  custom_states_msgs_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , controlX(0.0)
    , controlY(0.0)
    , controlYAW(0.0)
    , duration(0.0)
    , pre_x(0.0)
    , pre_y(0.0)
    , pre_yaw(0.0)
    , flag(false)
    , tf_flag(false)
    , diff_x(false)
    , diff_y(false)
    , diff_yaw(false)  {
    }
  custom_states_msgs_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , controlX(0.0)
    , controlY(0.0)
    , controlYAW(0.0)
    , duration(0.0)
    , pre_x(0.0)
    , pre_y(0.0)
    , pre_yaw(0.0)
    , flag(false)
    , tf_flag(false)
    , diff_x(false)
    , diff_y(false)
    , diff_yaw(false)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _controlX_type;
  _controlX_type controlX;

   typedef double _controlY_type;
  _controlY_type controlY;

   typedef double _controlYAW_type;
  _controlYAW_type controlYAW;

   typedef double _duration_type;
  _duration_type duration;

   typedef double _pre_x_type;
  _pre_x_type pre_x;

   typedef double _pre_y_type;
  _pre_y_type pre_y;

   typedef double _pre_yaw_type;
  _pre_yaw_type pre_yaw;

   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef uint8_t _tf_flag_type;
  _tf_flag_type tf_flag;

   typedef uint8_t _diff_x_type;
  _diff_x_type diff_x;

   typedef uint8_t _diff_y_type;
  _diff_y_type diff_y;

   typedef uint8_t _diff_yaw_type;
  _diff_yaw_type diff_yaw;





  typedef boost::shared_ptr< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct custom_states_msgs_

typedef ::dynamo_planner::custom_states_msgs_<std::allocator<void> > custom_states_msgs;

typedef boost::shared_ptr< ::dynamo_planner::custom_states_msgs > custom_states_msgsPtr;
typedef boost::shared_ptr< ::dynamo_planner::custom_states_msgs const> custom_states_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamo_planner::custom_states_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamo_planner::custom_states_msgs_<ContainerAllocator1> & lhs, const ::dynamo_planner::custom_states_msgs_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw &&
    lhs.controlX == rhs.controlX &&
    lhs.controlY == rhs.controlY &&
    lhs.controlYAW == rhs.controlYAW &&
    lhs.duration == rhs.duration &&
    lhs.pre_x == rhs.pre_x &&
    lhs.pre_y == rhs.pre_y &&
    lhs.pre_yaw == rhs.pre_yaw &&
    lhs.flag == rhs.flag &&
    lhs.tf_flag == rhs.tf_flag &&
    lhs.diff_x == rhs.diff_x &&
    lhs.diff_y == rhs.diff_y &&
    lhs.diff_yaw == rhs.diff_yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamo_planner::custom_states_msgs_<ContainerAllocator1> & lhs, const ::dynamo_planner::custom_states_msgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamo_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b52bf44a08210bd7d5f8e100b5f756a";
  }

  static const char* value(const ::dynamo_planner::custom_states_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b52bf44a08210bdULL;
  static const uint64_t static_value2 = 0x7d5f8e100b5f756aULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamo_planner/custom_states_msgs";
  }

  static const char* value(const ::dynamo_planner::custom_states_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# double type x y yaw control duration\n"
"float64 x\n"
"float64 y\n"
"float64 yaw\n"
"\n"
"float64 controlX\n"
"float64 controlY\n"
"float64 controlYAW\n"
"\n"
"float64 duration\n"
"\n"
"float64 pre_x\n"
"float64 pre_y\n"
"float64 pre_yaw\n"
"\n"
"bool flag\n"
"bool tf_flag\n"
"\n"
"bool diff_x\n"
"bool diff_y\n"
"bool diff_yaw\n"
;
  }

  static const char* value(const ::dynamo_planner::custom_states_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.controlX);
      stream.next(m.controlY);
      stream.next(m.controlYAW);
      stream.next(m.duration);
      stream.next(m.pre_x);
      stream.next(m.pre_y);
      stream.next(m.pre_yaw);
      stream.next(m.flag);
      stream.next(m.tf_flag);
      stream.next(m.diff_x);
      stream.next(m.diff_y);
      stream.next(m.diff_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_states_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamo_planner::custom_states_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamo_planner::custom_states_msgs_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "controlX: ";
    Printer<double>::stream(s, indent + "  ", v.controlX);
    s << indent << "controlY: ";
    Printer<double>::stream(s, indent + "  ", v.controlY);
    s << indent << "controlYAW: ";
    Printer<double>::stream(s, indent + "  ", v.controlYAW);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
    s << indent << "pre_x: ";
    Printer<double>::stream(s, indent + "  ", v.pre_x);
    s << indent << "pre_y: ";
    Printer<double>::stream(s, indent + "  ", v.pre_y);
    s << indent << "pre_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.pre_yaw);
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "tf_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tf_flag);
    s << indent << "diff_x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.diff_x);
    s << indent << "diff_y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.diff_y);
    s << indent << "diff_yaw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.diff_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMO_PLANNER_MESSAGE_CUSTOM_STATES_MSGS_H
