// Generated by gencpp from file dynamo_planner/physics_data_samplerResponse.msg
// DO NOT EDIT!


#ifndef DYNAMO_PLANNER_MESSAGE_PHYSICS_DATA_SAMPLERRESPONSE_H
#define DYNAMO_PLANNER_MESSAGE_PHYSICS_DATA_SAMPLERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamo_planner
{
template <class ContainerAllocator>
struct physics_data_samplerResponse_
{
  typedef physics_data_samplerResponse_<ContainerAllocator> Type;

  physics_data_samplerResponse_()
    : result(false)  {
    }
  physics_data_samplerResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct physics_data_samplerResponse_

typedef ::dynamo_planner::physics_data_samplerResponse_<std::allocator<void> > physics_data_samplerResponse;

typedef boost::shared_ptr< ::dynamo_planner::physics_data_samplerResponse > physics_data_samplerResponsePtr;
typedef boost::shared_ptr< ::dynamo_planner::physics_data_samplerResponse const> physics_data_samplerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator1> & lhs, const ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator1> & lhs, const ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamo_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamo_planner/physics_data_samplerResponse";
  }

  static const char* value(const ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool result\n"
"\n"
;
  }

  static const char* value(const ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct physics_data_samplerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamo_planner::physics_data_samplerResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMO_PLANNER_MESSAGE_PHYSICS_DATA_SAMPLERRESPONSE_H
