// Generated by gencpp from file dynamo_planner/physics_data_samplerRequest.msg
// DO NOT EDIT!


#ifndef DYNAMO_PLANNER_MESSAGE_PHYSICS_DATA_SAMPLERREQUEST_H
#define DYNAMO_PLANNER_MESSAGE_PHYSICS_DATA_SAMPLERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamo_planner
{
template <class ContainerAllocator>
struct physics_data_samplerRequest_
{
  typedef physics_data_samplerRequest_<ContainerAllocator> Type;

  physics_data_samplerRequest_()
    : NUM_STEP(0)  {
    }
  physics_data_samplerRequest_(const ContainerAllocator& _alloc)
    : NUM_STEP(0)  {
  (void)_alloc;
    }



   typedef int64_t _NUM_STEP_type;
  _NUM_STEP_type NUM_STEP;





  typedef boost::shared_ptr< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct physics_data_samplerRequest_

typedef ::dynamo_planner::physics_data_samplerRequest_<std::allocator<void> > physics_data_samplerRequest;

typedef boost::shared_ptr< ::dynamo_planner::physics_data_samplerRequest > physics_data_samplerRequestPtr;
typedef boost::shared_ptr< ::dynamo_planner::physics_data_samplerRequest const> physics_data_samplerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator1> & lhs, const ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.NUM_STEP == rhs.NUM_STEP;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator1> & lhs, const ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamo_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "521a14b05672e26237fdd5647755858f";
  }

  static const char* value(const ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x521a14b05672e262ULL;
  static const uint64_t static_value2 = 0x37fdd5647755858fULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamo_planner/physics_data_samplerRequest";
  }

  static const char* value(const ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 NUM_STEP\n"
;
  }

  static const char* value(const ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.NUM_STEP);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct physics_data_samplerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamo_planner::physics_data_samplerRequest_<ContainerAllocator>& v)
  {
    s << indent << "NUM_STEP: ";
    Printer<int64_t>::stream(s, indent + "  ", v.NUM_STEP);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMO_PLANNER_MESSAGE_PHYSICS_DATA_SAMPLERREQUEST_H
