controller_list:
  - name: fake_vehicle_controller
    joints:
      - base_x_joint
      - base_y_joint
      - base_z_joint
      - base_yaw_joint
  - name: fake_base_body_controller
    joints:
      - base_x_joint
      - base_y_joint
      - base_yaw_joint