# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: vehicle
  joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_x_joint
    - base_y_joint
    - base_z_joint
    - base_yaw_joint
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
vehicle_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - base_x_joint
    - base_y_joint
    - base_yaw_joint
  gains:
    base_x_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    base_y_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    base_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1