# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dynamo_planner/custom_states_msgs.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class custom_states_msgs(genpy.Message):
  _md5sum = "687ab8d67518730041fc3c6e12a166b7"
  _type = "dynamo_planner/custom_states_msgs"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# double type x y yaw control duration
float64 x
float64 y
float64 yaw

float64 controlA
float64 controlB
float64 control
float64 controlYAW

float64 duration

float64 pre_x
float64 pre_y
float64 pre_yaw
float64 pre_controlA
float64 pre_controlB

bool flag
bool sub_flag

int8 index
"""
  __slots__ = ['x','y','yaw','controlA','controlB','control','controlYAW','duration','pre_x','pre_y','pre_yaw','pre_controlA','pre_controlB','flag','sub_flag','index']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','bool','bool','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,yaw,controlA,controlB,control,controlYAW,duration,pre_x,pre_y,pre_yaw,pre_controlA,pre_controlB,flag,sub_flag,index

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(custom_states_msgs, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.controlA is None:
        self.controlA = 0.
      if self.controlB is None:
        self.controlB = 0.
      if self.control is None:
        self.control = 0.
      if self.controlYAW is None:
        self.controlYAW = 0.
      if self.duration is None:
        self.duration = 0.
      if self.pre_x is None:
        self.pre_x = 0.
      if self.pre_y is None:
        self.pre_y = 0.
      if self.pre_yaw is None:
        self.pre_yaw = 0.
      if self.pre_controlA is None:
        self.pre_controlA = 0.
      if self.pre_controlB is None:
        self.pre_controlB = 0.
      if self.flag is None:
        self.flag = False
      if self.sub_flag is None:
        self.sub_flag = False
      if self.index is None:
        self.index = 0
    else:
      self.x = 0.
      self.y = 0.
      self.yaw = 0.
      self.controlA = 0.
      self.controlB = 0.
      self.control = 0.
      self.controlYAW = 0.
      self.duration = 0.
      self.pre_x = 0.
      self.pre_y = 0.
      self.pre_yaw = 0.
      self.pre_controlA = 0.
      self.pre_controlB = 0.
      self.flag = False
      self.sub_flag = False
      self.index = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_13d2Bb().pack(_x.x, _x.y, _x.yaw, _x.controlA, _x.controlB, _x.control, _x.controlYAW, _x.duration, _x.pre_x, _x.pre_y, _x.pre_yaw, _x.pre_controlA, _x.pre_controlB, _x.flag, _x.sub_flag, _x.index))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 107
      (_x.x, _x.y, _x.yaw, _x.controlA, _x.controlB, _x.control, _x.controlYAW, _x.duration, _x.pre_x, _x.pre_y, _x.pre_yaw, _x.pre_controlA, _x.pre_controlB, _x.flag, _x.sub_flag, _x.index,) = _get_struct_13d2Bb().unpack(str[start:end])
      self.flag = bool(self.flag)
      self.sub_flag = bool(self.sub_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_13d2Bb().pack(_x.x, _x.y, _x.yaw, _x.controlA, _x.controlB, _x.control, _x.controlYAW, _x.duration, _x.pre_x, _x.pre_y, _x.pre_yaw, _x.pre_controlA, _x.pre_controlB, _x.flag, _x.sub_flag, _x.index))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 107
      (_x.x, _x.y, _x.yaw, _x.controlA, _x.controlB, _x.control, _x.controlYAW, _x.duration, _x.pre_x, _x.pre_y, _x.pre_yaw, _x.pre_controlA, _x.pre_controlB, _x.flag, _x.sub_flag, _x.index,) = _get_struct_13d2Bb().unpack(str[start:end])
      self.flag = bool(self.flag)
      self.sub_flag = bool(self.sub_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13d2Bb = None
def _get_struct_13d2Bb():
    global _struct_13d2Bb
    if _struct_13d2Bb is None:
        _struct_13d2Bb = struct.Struct("<13d2Bb")
    return _struct_13d2Bb
